services:
  - type: web
    name: maevie-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://maevieprojectmanager.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: maevie-db
          property: connectionString

databases:
  - name: maevie-db
    plan: free
    databaseName: maevie
    user: maevie_user
